### ISSUE TITLE
Feature request: Mac Catalyst support

### ISSUE THREAD

**Issue by MikeChongCan** [human-solutions/xcframework#3]
A low-priority request: The nightly compiler now supports Mac Catalyst ([example](https://github.com/imWildCat/uniffi-rs-fullstack-examples/blob/main/hello/Makefile#L13-L14)).

If needed, I could start a PR for it.

**Comment by akesson** [comment]
Sure, that would be great!

**Comment by MikeChongCan** [comment]
Mac Catalyst would require nightly toolchain. Because they are at Tier 3 (https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-3).

I found currently, the design of `xcframework` would require the user to specify whether it is nightly, like `cargo +nightly xcframework`. But in most use cases, we would build iOS and macOS using stable, and Catalyst using nightly.

What do you think of the design of Catalyst support?

(no rush)

**Comment by akesson** [comment]
Will you use the Catalyst support? If not, then I suggest waiting until someone needs it.

You should probably use something like [rustversion](https://crates.io/crates/rustversion) to conditionally build the support for Catalyst only on nightly. However, from my experience, it ends up being much harder to maintain. Would probably be best to add GitHub CI for automatically testing both stable and nightly compiles.

**Comment by MikeChongCan** [comment]
ok! I actually have some custom script which have similar functionality with `xcframework`.

I think we can hold on the implementation of Catalyst.

> Would probably be best to add GitHub CI for automatically testing both stable and nightly compiles.

That's also what I expect. Maybe I can raise a small PR to set up GH Actions.

**Comment by akesson** [comment]
Yes please do. And include the checks: `cargo fmt --check` and `cargo clippy -- -Dwarnings`. 😄

**Comment by akesson** [comment]
@imWildCat I'll close this ticket unless you are still interested in creating a PR for it.

**Comment by MikeChongCan** [comment]
ok sure
